//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHS.Web.Hel_FHIR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnaReportingEntities : DbContext
    {
        public AnaReportingEntities()
            : base("name=AnaReportingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RequestLog> RequestLogs { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<RequestLogDetail> RequestLogDetails { get; set; }
    }
}
