//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHS.Web.Hel_FHIR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public System.DateTime Person_Update_Dt_Tm { get; set; }
        public System.DateTime Person_Create_Dt_Tm { get; set; }
        public int Person_Id { get; set; }
        public int Person_MRN { get; set; }
        public string Person_Name_First { get; set; }
        public string Person_Name_Last { get; set; }
        public string Person_Name_Middle { get; set; }
        public string Person_Name_Full_Format { get; set; }
        public Nullable<System.DateTime> Person_Abs_Birth_Dt_Tm { get; set; }
        public string Person_Sex { get; set; }
        public string Person_Ethnic_Group { get; set; }
        public string Person_Race { get; set; }
        public string Person_Language { get; set; }
        public string Person_Marital_Type { get; set; }
        public string Person_VIP { get; set; }
        public string Person_SSN { get; set; }
        public Nullable<int> Person_Current_Age { get; set; }
        public string Preferred_First_Name_First { get; set; }
        public string Vet_Per_Info_Value { get; set; }
        public string Vet_Status_Per_Info_Value { get; set; }
        public string Mail_Addr_Per_Addr_City { get; set; }
        public string Mail_Addr_Per_Addr_State { get; set; }
        public string Mail_Addr_Per_Addr_Street_1 { get; set; }
        public string Mail_Addr_Per_Addr_Street_2 { get; set; }
        public string Mail_Addr_Per_Addr_Zip { get; set; }
        public string Mail_Addr_Per_Addr_County { get; set; }
        public string Hm_Phn_Number { get; set; }
        public string Per_Email__Addr_Type_ { get; set; }
        public string Mobile_ph_Per_Phn_Phone_Number { get; set; }
        public string Pref_Contact_Per_Phn_Contact_Method { get; set; }
        public string Pref_Contact_Per_Pat_Callback_Consent { get; set; }
        public string Pref_Contact_Per_Phn_Txt_Permission { get; set; }
        public string Hm_Addr_City { get; set; }
        public string Hm_Addr_County { get; set; }
        public string Hm_Addr_State { get; set; }
        public string Hm_Addr_Street_1 { get; set; }
        public string Hm_Addr_Street_2 { get; set; }
        public string Hm_Addr_Zip { get; set; }
    }
}
