//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHS.Web.Hel_FHIR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestLog
    {
        public int helFhirLogId { get; set; }
        public System.DateTime requestStamp { get; set; }
        public string userName { get; set; }
        public string userStation { get; set; }
        public int patientMRN { get; set; }
        public string requestDomain { get; set; }
        public string requestUrl { get; set; }
        public int requestStatusCode { get; set; }
        public string requestStatusMessage { get; set; }
        public string phiSource { get; set; }
    }
}
