//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHS.Web.Hel_FHIR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestLogDetail
    {
        public int helFhirLogDetailId { get; set; }
        public int helFhirLogId { get; set; }
        public string referenceUrl { get; set; }
        public string informationSourceNode { get; set; }
        public string informationSource { get; set; }
    }
}
